version: '3'

services:
  zap:
    image: ghcr.io/zaproxy/zaproxy:latest  # âœ… updated working ZAP image
    container_name: zap
    tty: true
    networks:
      - scan_net
    ports:
      - "8090:8080"  # Optional: expose ZAP if needed
    volumes:
      - ./reports:/zap/reports
    command: ["zap.sh", "-daemon", "-host", "0.0.0.0", "-port", "8080", "-config", "api.disablekey=true"]

  jenkins:
    jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "9090:8080"  # host:container
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - scan_net

networks:
  scan_net:

